name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run:  echo "Hello World! From Git Hub Actions"
      - name: Print Goobye
        run: echo "Done! Bye for now!"
